// <auto-generated />
namespace RPG_Guia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class LoginGitPush : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LoginGitPush));
        
        string IMigrationMetadata.Id
        {
            get { return "202001032243211_LoginGitPush"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
